#! /bin/sh
# SPDX-License-Identifier: MIT

if test \! -d $EVL_TESTDIR; then
   echo >&2 "$EVL_TESTDIR not found - broken installation?"
   exit 2
fi

usage() {
   echo >&2 "usage: $(basename $1) [-l][-L][-k][-r][-h] [test-list]"
}

help=false
keep_going=false
repeat=false
do_list=false
full_path=false
test_args=false
test_arg_list=
test_list=

while test $# -gt 0
do
    if test x$test_args = xtrue; then
	test_arg_list="$test_arg_list $1"
	shift
    else
	case "$1" in
	    -k) keep_going=true;
		shift;;
	    -r) repeat=true;
		shift;;
	    -h) help=true;
		shift;;
	    -l) do_list=true;
		shift;;
	    -L) full_path=true;
		do_list=true;
		shift;;
	    --) test_args=true
		shift;;
	    -@) echo "run the EVL tests"
	        exit 0;;
	    -*) usage $0
		exit 1;;
	    *)  test_list="$test_list $(eval echo $EVL_TESTDIR/$1)"
		shift;;
	esac
    fi
done

if test x$help = xtrue; then
   usage $0
   exit 0
fi

unset EVL_ON_VM
if $(systemd-detect-virt --vm --quiet 2>/dev/null); then
    export EVL_ON_VM=y
fi

if test -z "$test_list"; then
   test_list="$(find $EVL_TESTDIR -maxdepth 1 -type f | sort)"
   if test -z "$test_list"; then
      echo >&2 "$EVL_TESTDIR is empty - broken installation?"
      exit 2
   fi
fi

if test x$do_list = xtrue; then
   for t in $test_list; do
       if test x$full_path = xtrue; then
	   echo "$t";
       else
	   echo "$(basename $t)"
       fi
   done
   exit 0
fi

result=0

while : ; do
      for t in $test_list; do
	  test \! -x $t && echo "$(basename $0): $(basename $t): no such test" && exit 2
	  # Swap stdout<->stderr for the test, capturing stderr into $log.
	  log=$($t $test_arg_list 3>&1 1>&2 2>&3)
	  status=$?
	  if test $status = 43; then
	      echo "$(basename $t): $log"
	  else
	      test -n "$log" && echo "$log"
	      if test $status = 0; then
		  echo "$(basename $t): OK"
	      elif test $status = 42; then
		  echo "$(basename $t): no kernel support"
	      else
		  echo "** $(basename $t): BROKEN"
		  result=$status
		  test x$keep_going = xfalse && break
	      fi
	  fi
      done
      test x$repeat = xfalse && break
done

exit $result
