#! /bin/sh
# SPDX-License-Identifier: MIT

usage() {
   echo >&2 "usage: $(basename $1) <debuggee> -- <gdb-args>"
}

help=false
gdb_args=false
gdb_arg_list=
debuggee=

for opt
do
    if test x$gdb_args = xtrue; then
	gdb_arg_list="$gdb_arg_list $opt"
    else
	case "$opt" in
	    -h) help=true;
		shift;;
	    --) gdb_args=true
		shift;;
	    -@) echo "debug EVL command plugin with GDB"
	        exit 0;;
	    -*) usage $0
		exit 1;;
	    *)  debuggee="$(eval echo $EVL_CMDDIR/evl-$opt)"
	esac
    fi
done

if test x$help = xtrue; then
   usage $0
   exit 0
fi

if test x$debuggee = x; then
   usage $0
   exit 2
fi

if test \! -f $debuggee; then
   echo >&2 "$(basename $0): cannot find $debuggee"
   exit 2
fi

export EVL_CMDDIR
export EVL_TESTDIR
export EVL_SYSDIR
export EVL_TRACEDIR
shift

gdb $debuggee $gdb_arg_list
